server.ip=localhost
#server.ip=20.191.158.196

server.port=80
#/page/+xxx+.html
spring.mvc.view.prefix=/page/
spring.mvc.view.suffix=.html

#sql server database
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Aiden;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=1234

#spring.datasource.username=sa
#spring.datasource.password=P@ssw0rd

#spring data JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#java mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=allen48692@gmail.com
spring.mail.password=xwzr iwse szld xbvl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#paypal
paypal.mode=sandbox
paypal.client.id=AXq5heL_hNFxqFkQH-bjRLoTk3NBwpv-9_maF96jWXPYGjDj7h6m7kGVY-oSgB446mPDui9yFHgwtgfh
paypal.client.secret=EPff74yAZZrrr-G5IbbbMfcXQWi5iT2vfoTzHJJjFGHywNxluyvP2zxO3Umx7uLTPwK3yqhQFDknf_be